<?xml version="1.0"?>
<package format="3">
  <name>lidar_obstacle_sim</name>
  <version>0.0.1</version>
  <description>Gazebo を用いた LiDAR 障害物検知の簡易シミュレータ。</description>
  <maintainer email="example@example.com">tc2025 team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros2launch</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
